import axios from "axios";
import { validateDataObject } from "./utils.js";

/**
 * Exchanges an authorization code for an access token.
 * 
 * @example
 * import { getOauthToken } from "@kash.88/alerts";
 * 
 * // The `code` is received after the user authorizes your application
 * // via the link generated by `getAuthorizeLink`.
 * 
 * try {
 *   const tokenData = await getOauthToken({
 *     client_id: '12345',
 *     client_secret: 'YOUR_CLIENT_SECRET',
 *     code: 'AUTHORIZATION_CODE'
 *   });
 *   console.log(tokenData.access_token);
 * } catch (error) {
 *   console.error('Error getting Oauth token:', error.response.data);
 * }
 * 
 * @param {object} data - The data for the token request.
 * @param {string|number} data.client_id - Your application's client ID.
 * @param {string} data.client_secret - Your application's client secret.
 * @param {string} data.code - The authorization code.
 * @param {string} [data.redirect_uri] - The same redirect URI used to obtain the authorization code.
 * @returns {Promise<object>} A promise that resolves to the token data from the API.
 * @see {@link https://www.donationalerts.com/apidoc#authorization__authorization_code__getting_access_token}
 */
export default async function getOauthToken(data) {
    validateDataObject(data, ['client_id', 'client_secret', 'code']);

    const response = await axios.post('https://www.donationalerts.com/oauth/token', {
        grant_type: 'authorization_code',
        client_id: data.client_id,
        client_secret: data.client_secret,
        code: data.code
    });

    return response.data;
}